### ISSUE TITLE
Define a Definition of Ready

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/uds-infra#3]
As a maintainer of UDS Infra, I want to understand everything I need to know for an issue to be worked, so that I am able to execute on the work without needing additional context.

Acceptance Criteria:

- CONTRIBUTING.md contains a Definiton of Ready that states that an issue needs to answer the following questions before it is ready to be picked up and worked:
    - What is being requested?
    - Who is requesting it?
    - Why is it needed?
    - How do we know that we are done?

Notes:
- Add a Definition of Ready to the Contributor Guide
- Should be very lightweight. Initial idea is just "Is the issue clear, concise, and actionable?"

Context: New issues get added to the "No Status" column in the project. For the issue to move to the "Todo" column it should meet the Definition of Ready as a candidate for any developer to pick up and work.

**Comment by wirewc** [comment]
Where will this document live?

**Comment by RothAndrew** [comment]
I'm thinking it would live in CONTRIBUTING.md
